// GENERATED by scripts/generate-icons.mjs — do not edit by hand.
// Glyph data extracted from lucide-static (ISC license).
export type GlyphElement = {
  tag: 'path' | 'circle' | 'line' | 'rect' | 'polyline' | 'polygon';
  props: Record<string, string | number>;
};

export const iconGlyphs: Record<string, GlyphElement[]> = {
  "search": [
    {
      "tag": "path",
      "props": {
        "d": "m21 21-4.34-4.34"
      }
    },
    {
      "tag": "circle",
      "props": {
        "cx": 11,
        "cy": 11,
        "r": 8
      }
    }
  ],
  "plus": [
    {
      "tag": "path",
      "props": {
        "d": "M5 12h14"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M12 5v14"
      }
    }
  ],
  "x": [
    {
      "tag": "path",
      "props": {
        "d": "M18 6 6 18"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "m6 6 12 12"
      }
    }
  ],
  "check": [
    {
      "tag": "path",
      "props": {
        "d": "M20 6 9 17l-5-5"
      }
    }
  ],
  "file-text": [
    {
      "tag": "path",
      "props": {
        "d": "M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M14 2v5a1 1 0 0 0 1 1h5"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M10 9H8"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M16 13H8"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M16 17H8"
      }
    }
  ],
  "folder": [
    {
      "tag": "path",
      "props": {
        "d": "M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z"
      }
    }
  ],
  "folder-open": [
    {
      "tag": "path",
      "props": {
        "d": "m6 14 1.5-2.9A2 2 0 0 1 9.24 10H20a2 2 0 0 1 1.94 2.5l-1.54 6a2 2 0 0 1-1.95 1.5H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H18a2 2 0 0 1 2 2v2"
      }
    }
  ],
  "inbox": [
    {
      "tag": "polyline",
      "props": {
        "points": "22 12 16 12 14 15 10 15 8 12 2 12"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M5.45 5.11 2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z"
      }
    }
  ],
  "message-circle": [
    {
      "tag": "path",
      "props": {
        "d": "M2.992 16.342a2 2 0 0 1 .094 1.167l-1.065 3.29a1 1 0 0 0 1.236 1.168l3.413-.998a2 2 0 0 1 1.099.092 10 10 0 1 0-4.777-4.719"
      }
    }
  ],
  "sparkles": [
    {
      "tag": "path",
      "props": {
        "d": "M11.017 2.814a1 1 0 0 1 1.966 0l1.051 5.558a2 2 0 0 0 1.594 1.594l5.558 1.051a1 1 0 0 1 0 1.966l-5.558 1.051a2 2 0 0 0-1.594 1.594l-1.051 5.558a1 1 0 0 1-1.966 0l-1.051-5.558a2 2 0 0 0-1.594-1.594l-5.558-1.051a1 1 0 0 1 0-1.966l5.558-1.051a2 2 0 0 0 1.594-1.594z"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M20 2v4"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M22 4h-4"
      }
    },
    {
      "tag": "circle",
      "props": {
        "cx": 4,
        "cy": 20,
        "r": 2
      }
    }
  ],
  "settings": [
    {
      "tag": "path",
      "props": {
        "d": "M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915"
      }
    },
    {
      "tag": "circle",
      "props": {
        "cx": 12,
        "cy": 12,
        "r": 3
      }
    }
  ],
  "chevron-right": [
    {
      "tag": "path",
      "props": {
        "d": "m9 18 6-6-6-6"
      }
    }
  ],
  "chevron-down": [
    {
      "tag": "path",
      "props": {
        "d": "m6 9 6 6 6-6"
      }
    }
  ],
  "chevron-left": [
    {
      "tag": "path",
      "props": {
        "d": "m15 18-6-6 6-6"
      }
    }
  ],
  "arrow-left": [
    {
      "tag": "path",
      "props": {
        "d": "m12 19-7-7 7-7"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M19 12H5"
      }
    }
  ],
  "trash-2": [
    {
      "tag": "path",
      "props": {
        "d": "M10 11v6"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M14 11v6"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M3 6h18"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"
      }
    }
  ],
  "pencil": [
    {
      "tag": "path",
      "props": {
        "d": "M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "m15 5 4 4"
      }
    }
  ],
  "grip-vertical": [
    {
      "tag": "circle",
      "props": {
        "cx": 9,
        "cy": 12,
        "r": 1
      }
    },
    {
      "tag": "circle",
      "props": {
        "cx": 9,
        "cy": 5,
        "r": 1
      }
    },
    {
      "tag": "circle",
      "props": {
        "cx": 9,
        "cy": 19,
        "r": 1
      }
    },
    {
      "tag": "circle",
      "props": {
        "cx": 15,
        "cy": 12,
        "r": 1
      }
    },
    {
      "tag": "circle",
      "props": {
        "cx": 15,
        "cy": 5,
        "r": 1
      }
    },
    {
      "tag": "circle",
      "props": {
        "cx": 15,
        "cy": 19,
        "r": 1
      }
    }
  ],
  "pin": [
    {
      "tag": "path",
      "props": {
        "d": "M12 17v5"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M9 10.76a2 2 0 0 1-1.11 1.79l-1.78.9A2 2 0 0 0 5 15.24V16a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-.76a2 2 0 0 0-1.11-1.79l-1.78-.9A2 2 0 0 1 15 10.76V7a1 1 0 0 1 1-1 2 2 0 0 0 0-4H8a2 2 0 0 0 0 4 1 1 0 0 1 1 1z"
      }
    }
  ],
  "pin-off": [
    {
      "tag": "path",
      "props": {
        "d": "M12 17v5"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M15 9.34V7a1 1 0 0 1 1-1 2 2 0 0 0 0-4H7.89"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "m2 2 20 20"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M9 9v1.76a2 2 0 0 1-1.11 1.79l-1.78.9A2 2 0 0 0 5 15.24V16a1 1 0 0 0 1 1h11"
      }
    }
  ],
  "archive": [
    {
      "tag": "rect",
      "props": {
        "width": 20,
        "height": 5,
        "x": 2,
        "y": 3,
        "rx": 1
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M4 8v11a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M10 12h4"
      }
    }
  ],
  "send": [
    {
      "tag": "path",
      "props": {
        "d": "M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11z"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "m21.854 2.147-10.94 10.939"
      }
    }
  ],
  "square": [
    {
      "tag": "rect",
      "props": {
        "width": 18,
        "height": 18,
        "x": 3,
        "y": 3,
        "rx": 2
      }
    }
  ],
  "download": [
    {
      "tag": "path",
      "props": {
        "d": "M12 15V3"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "m7 10 5 5 5-5"
      }
    }
  ],
  "info": [
    {
      "tag": "circle",
      "props": {
        "cx": 12,
        "cy": 12,
        "r": 10
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M12 16v-4"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M12 8h.01"
      }
    }
  ],
  "circle-alert": [
    {
      "tag": "circle",
      "props": {
        "cx": 12,
        "cy": 12,
        "r": 10
      }
    },
    {
      "tag": "line",
      "props": {}
    },
    {
      "tag": "line",
      "props": {}
    }
  ],
  "wifi-off": [
    {
      "tag": "path",
      "props": {
        "d": "M12 20h.01"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M8.5 16.429a5 5 0 0 1 7 0"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M5 12.859a10 10 0 0 1 5.17-2.69"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M19 12.859a10 10 0 0 0-2.007-1.523"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M2 8.82a15 15 0 0 1 4.177-2.643"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M22 8.82a15 15 0 0 0-11.288-3.764"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "m2 2 20 20"
      }
    }
  ],
  "file-plus-2": [
    {
      "tag": "path",
      "props": {
        "d": "M11.35 22H6a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.706.706l3.588 3.588A2.4 2.4 0 0 1 20 8v5.35"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M14 2v5a1 1 0 0 0 1 1h5"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M14 19h6"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M17 16v6"
      }
    }
  ],
  "folder-plus": [
    {
      "tag": "path",
      "props": {
        "d": "M12 10v6"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M9 13h6"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z"
      }
    }
  ],
  "corner-down-right": [
    {
      "tag": "path",
      "props": {
        "d": "m15 10 5 5-5 5"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M4 4v7a4 4 0 0 0 4 4h12"
      }
    }
  ],
  "book-open": [
    {
      "tag": "path",
      "props": {
        "d": "M12 5v16"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M20.001 19A2 2 0 0022 17V5a2 2 0 00-1.999-2L16 3.002A5 5 0 0012 5a5 5 0 00-4-2H4a2 2 0 00-2 2v12a2 2 0 001.999 2H8a5 5 0 014 2 5 5 0 014-2z"
      }
    }
  ],
  "lightbulb": [
    {
      "tag": "path",
      "props": {
        "d": "M15 14c.2-1 .7-1.7 1.5-2.5 1-.9 1.5-2.2 1.5-3.5A6 6 0 0 0 6 8c0 1 .2 2.2 1.5 3.5.7.7 1.3 1.5 1.5 2.5"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M9 18h6"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M10 22h4"
      }
    }
  ],
  "rotate-ccw": [
    {
      "tag": "path",
      "props": {
        "d": "M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M3 3v5h5"
      }
    }
  ],
  "copy": [
    {
      "tag": "rect",
      "props": {
        "width": 14,
        "height": 14,
        "x": 8,
        "y": 8,
        "rx": 2,
        "ry": 2
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"
      }
    }
  ],
  "ellipsis-vertical": [
    {
      "tag": "circle",
      "props": {
        "cx": 12,
        "cy": 12,
        "r": 1
      }
    },
    {
      "tag": "circle",
      "props": {
        "cx": 12,
        "cy": 5,
        "r": 1
      }
    },
    {
      "tag": "circle",
      "props": {
        "cx": 12,
        "cy": 19,
        "r": 1
      }
    }
  ],
  "list-tree": [
    {
      "tag": "path",
      "props": {
        "d": "M8 5h13"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M13 12h8"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M13 19h8"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M3 10a2 2 0 0 0 2 2h3"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M3 5v12a2 2 0 0 0 2 2h3"
      }
    }
  ],
  "scan-search": [
    {
      "tag": "path",
      "props": {
        "d": "M3 7V5a2 2 0 0 1 2-2h2"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M17 3h2a2 2 0 0 1 2 2v2"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M21 17v2a2 2 0 0 1-2 2h-2"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M7 21H5a2 2 0 0 1-2-2v-2"
      }
    },
    {
      "tag": "circle",
      "props": {
        "cx": 12,
        "cy": 12,
        "r": 3
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "m16 16-1.9-1.9"
      }
    }
  ],
  "sliders-horizontal": [
    {
      "tag": "path",
      "props": {
        "d": "M10 5H3"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M12 19H3"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M14 3v4"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M16 17v4"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M21 12h-9"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M21 19h-5"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M21 5h-7"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M8 10v4"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M8 12H3"
      }
    }
  ],
  "cpu": [
    {
      "tag": "path",
      "props": {
        "d": "M12 20v2"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M12 2v2"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M17 20v2"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M17 2v2"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M2 12h2"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M2 17h2"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M2 7h2"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M20 12h2"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M20 17h2"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M20 7h2"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M7 20v2"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M7 2v2"
      }
    },
    {
      "tag": "rect",
      "props": {
        "x": 4,
        "y": 4,
        "width": 16,
        "height": 16,
        "rx": 2
      }
    },
    {
      "tag": "rect",
      "props": {
        "x": 8,
        "y": 8,
        "width": 8,
        "height": 8,
        "rx": 1
      }
    }
  ],
  "hard-drive": [
    {
      "tag": "path",
      "props": {
        "d": "M10 16h.01"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M2.212 11.577a2 2 0 0 0-.212.896V18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-5.527a2 2 0 0 0-.212-.896L18.55 5.11A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M21.946 12.013H2.054"
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "M6 16h.01"
      }
    }
  ],
  "circle-check": [
    {
      "tag": "circle",
      "props": {
        "cx": 12,
        "cy": 12,
        "r": 10
      }
    },
    {
      "tag": "path",
      "props": {
        "d": "m9 12 2 2 4-4"
      }
    }
  ]
} as const;
