// Generates src/ui/iconGlyphs.generated.ts from lucide-static SVGs.
// Lucide icons are ISC-licensed; glyphs are extracted verbatim (no CDN at runtime).
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const iconsDir = join(here, '..', 'node_modules', 'lucide-static', 'icons');

// Icons used across the app. Keep in sync with IconName in src/ui/Icon.tsx.
const ICONS = [
  'search', 'plus', 'x', 'check', 'file-text', 'folder', 'folder-open',
  'inbox', 'message-circle', 'sparkles', 'settings', 'chevron-right',
  'chevron-down', 'chevron-left', 'arrow-left', 'trash-2', 'pencil',
  'grip-vertical', 'pin', 'pin-off', 'archive', 'send', 'square',
  'download', 'info', 'circle-alert', 'wifi-off', 'file-plus-2',
  'folder-plus', 'corner-down-right', 'book-open', 'lightbulb',
  'rotate-ccw', 'copy', 'ellipsis-vertical', 'list-tree', 'scan-search',
  'sliders-horizontal', 'cpu', 'hard-drive', 'circle-check',
];

const ATTRS = ['d', 'cx', 'cy', 'r', 'x1', 'y1', 'x2', 'y2', 'x', 'y', 'width', 'height', 'rx', 'ry', 'points'];
const NUMERIC = new Set(['cx', 'cy', 'r', 'x1', 'y1', 'x2', 'y2', 'x', 'y', 'width', 'height', 'rx', 'ry']);

const out = {};
const missing = [];
for (const name of ICONS) {
  let svg;
  try {
    svg = readFileSync(join(iconsDir, `${name}.svg`), 'utf8');
  } catch {
    missing.push(name);
    continue;
  }
  const elements = [];
  const re = /<(path|circle|line|rect|polyline|polygon)\s+([^/>]*)\/>/g;
  let m;
  while ((m = re.exec(svg)) !== null) {
    const [, tag, attrStr] = m;
    const props = {};
    const attrRe = /([a-zA-Z-]+)="([^"]*)"/g;
    let a;
    while ((a = attrRe.exec(attrStr)) !== null) {
      const [, key, value] = a;
      if (!ATTRS.includes(key)) continue;
      props[key] = NUMERIC.has(key) ? Number(value) : value;
    }
    elements.push({ tag, props });
  }
  out[name] = elements;
}

if (missing.length) {
  console.error('Missing icons:', missing.join(', '));
  process.exit(1);
}

const header = `// GENERATED by scripts/generate-icons.mjs — do not edit by hand.
// Glyph data extracted from lucide-static (ISC license).
export type GlyphElement = {
  tag: 'path' | 'circle' | 'line' | 'rect' | 'polyline' | 'polygon';
  props: Record<string, string | number>;
};

export const iconGlyphs: Record<string, GlyphElement[]> = `;

writeFileSync(
  join(here, '..', 'src', 'ui', 'iconGlyphs.generated.ts'),
  header + JSON.stringify(out, null, 2) + ' as const;\n'
);
console.log(`Generated ${Object.keys(out).length} icons.`);
